steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/lyrical-bolt-444918-p7/student-workflow:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/lyrical-bolt-444918-p7/student-workflow:latest']
  - name: 'gcr.io/cloud-builders/kubectl'
    env:
      - 'USE_GKE_GCLOUD_AUTH_PLUGIN=True'
      - 'CLOUDSDK_CONTAINER_CLUSTER=student-workflow-cluster'
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    args:
      - 'set'
      - 'image'
      - 'deployment/student-workflow'
      - 'student-workflow=gcr.io/lyrical-bolt-444918-p7/student-workflow:latest'
serviceAccount: projects/lyrical-bolt-444918-p7/serviceAccounts/cloud-build@lyrical-bolt-444918-p7.iam.gserviceaccount.com
images:
  - 'gcr.io/lyrical-bolt-444918-p7/student-workflow:latest'
options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
