steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/lyrical-bolt-444918-p7/student-workflow:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/lyrical-bolt-444918-p7/student-workflow:latest']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['container', 'clusters', 'get-credentials', 'student-workflow-cluster', '--zone', 'us-central1-a', '--project', 'lyrical-bolt-444918-p7']
  - name: 'gcr.io/cloud-builders/kubectl'
    env:
      - 'CLOUDSDK_CONTAINER_CLUSTER=student-workflow-cluster'
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    args:
      - 'set'
      - 'image'
      - '--namespace=default'
      - 'deployment/student-workflow'
      - 'student-workflow=gcr.io/lyrical-bolt-444918-p7/student-workflow:latest'
