steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/lyrical-bolt-444918-p7/student-workflow:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/lyrical-bolt-444918-p7/student-workflow:latest']
  - name: 'gcr.io/cloud-builders/kubectl'
    env:
    - 'CLOUDSDK_COMPUTE_REGION=us-central1'
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=student-workflow-cluster'
    args:
      - '--namespace=student-workflow'
      - 'set'
      - 'image'
      - 'deployment/student-workflow'
      - 'student-workflow=gcr.io/lyrical-bolt-444918-p7/student-workflow:latest'

images:
  - 'gcr.io/lyrical-bolt-444918-p7/student-workflow:latest'

options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET

  
