steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/lyrical-bolt-444918-p7/student-workflow:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/lyrical-bolt-444918-p7/student-workflow:latest']
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/student-workflow'
      - 'student-workflow=gcr.io/lyrical-bolt-444918-p7/student-workflow:latest'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=student-workflow-cluster'
images:
  - 'gcr.io/lyrical-bolt-444918-p7/student-workflow:latest'
